version: v1

labels:
  - label: 'maintenance'
    sync: true
    matcher:
      title: '^Upgrade(|!): .+'

  - label: 'documentation'
    sync: true
    matcher:
      title: '^Docs(|!): .+'

  - label: 'enhancement'
    sync: true
    matcher:
      title: '^New(|!): .+'

  - label: 'bug'
    sync: true
    matcher:
      title: '^Fix(|!): .+'

  - label: 'refactor'
    sync: true
    matcher:
      title: '^Refactor(|!): .+'

  - label: 'test'
    sync: true
    matcher:
      title: '^Test(|!): .+'

  - label: 'breaking'
    sync: true
    matcher:
      title: '^[a-z]+!: .+'

  - label: 'dependencies'
    sync: true
    matcher:
      files:
        any:
          - 'composer.json'
          - 'composer.lock'
          - 'package.json'
          - 'pnpm-lock.yaml'

checks:
  - context: 'Semantic Pull Request'
    description:
      success: Ready for review.
      failure: Missing semantic label.
    labels:
      any:
        - bugfix
        - documentation
        - enhancement
        - maintenance
